docs/website/static/css/custom.css
Signed-off-by: Jan Okraska <jan.okraska@cern.ch>
=> docs: styling- center footer divs

demo/src/Results.js, demo/src/index.js, src/api/SearchApi.js, src/components/ActiveAggregations/ActiveAggregations.js, src/components/Aggregator/Aggregator.js, src/components/Aggregator/AggregatorValues.js
* refactored code that displays nested aggregations
=> searchapi: aggregator changes

CHANGES.md, demo/src/index.js, docs/docs/components/withQueryState.md, docs/website/i18n/en.json, docs/website/sidebars.json, package.json, src/api/InvenioSearchApi.js, src/components/HOC/index.js, src/components/HOC/withQueryState.js, src/components/index.js, src/contrib/invenio/serializers.js, src/store.js
- Adds a new HOC component `withQueryState` which enables an external component to read the state.
- NOTE: The connected component *must* be child of the `ReactSearchkit` component.
=> components: QueryState HOC

package-lock.json, package.json, src/index.js, src/lib/components/ReactSearchKit/ReactSearchKit.js
* moves the hardcoded import of React-Semantic-UI outside the library to
allow theming
* upgrades create-react-app to the latest
=> theming: fix Semantic-UI import

src/lib/components/Pagination/Pagination.js
* enables passing semantic-ui props
=> pagination: allow passing props

rollup.config.js
=> build: fix CommonJS build to remove strict directive

CHANGES.md, package-lock.json, package.json, src/lib/api/UrlHandlerApi.js, src/lib/api/contrib/invenio/InvenioRequestSerializer.js, src/lib/components/ReactSearchKit/ReactSearchKit.js, src/lib/store.js, src/lib/storeConfig.js
=> searchApi: add hidden parameters option

src/lib/api/contrib/invenio/InvenioRequestSerializer.js
* closes inveniosoftware/react-invenio-app-ils#219
=> api: fix broken multiple filter selection in invenio serializer

src/lib/components/Sort/Sort.js
* Closes https://github.com/inveniosoftware/invenio-app-rdm/issues/332
=> sort: removes 'compact' from dropdown

README.md, src/lib/components/ActiveFilters/index.js, src/lib/components/AutocompleteSearchBar/index.js, src/lib/components/Bootstrap/index.js, src/lib/components/BucketAggregation/index.js, src/lib/components/Count/index.js, src/lib/components/EmptyResults/index.js, src/lib/components/Error/index.js, src/lib/components/HOC/withState.js, src/lib/components/LayoutSwitcher/index.js, src/lib/components/Pagination/index.js, src/lib/components/ResultsGrid/index.js, src/lib/components/ResultsList/index.js, src/lib/components/ResultsLoader/index.js, src/lib/components/ResultsMultiLayout/index.js, src/lib/components/ResultsPerPage/index.js, src/lib/components/SearchBar/index.js, src/lib/components/Sort/index.js, src/lib/components/SortBy/index.js, src/lib/components/SortOrder/index.js, src/lib/components/Toggle/index.js, src/lib/store.js
=> remove connectExtend

src/lib/components/BucketAggregation/BucketAggregationValues.js
* Adds check for boolean values on aggs
Fixes boolean filter when selected
closes https://github.com/inveniosoftware/react-searchkit/issues/56
=> aggs: Fixes boolean values bug

src/lib/api/UrlHandlerApi.js, src/lib/api/UrlHandlerApi.test.js, src/lib/api/UrlParamValidator.js, src/lib/api/index.js
* addresses inveniosoftware/react-invenio-app-ils#128
* also exposes the class `UrlParamValidator` in case one needs to build a stricter validator on top of it (for instance, ensure the provided page size is indeed an option of the dropdown)
=> handle malformed urls

src/lib/components/BucketAggregation/BucketAggregation.js
* closes https://github.com/inveniosoftware/react-invenio-app-ils/issues/22
=> aggs: Allows objects to be passed as aggs

src/lib/api/UrlHandlerApi.js, src/lib/api/UrlHandlerApi.test.js, src/lib/state/reducers/query.js
=> Fix parsing complex string from URL params

src/lib/api/contrib/invenio/InvenioRecordsResourcesRequestSerializer.js, src/lib/api/contrib/invenio/InvenioRecordsResourcesRequestSerializer.test.js, src/lib/api/contrib/invenio/InvenioSearchApi.js, src/lib/api/contrib/invenio/index.js, src/lib/components/Error/Error.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/440
closes https://github.com/inveniosoftware/react-searchkit/issues/180
=> api-contrib: Add request serializer for invenio-records-resources

CHANGES.md, package-lock.json, package.json, src/lib/components/BucketAggregation/BucketAggregation.js, src/lib/state/actions/query.js, src/lib/state/selectors/query.js, src/lib/state/selectors/query.test.js
closes https://github.com/inveniosoftware/invenio-app-rdm/issues/1014
=> facets: fix nested facet deselection

src/lib/components/EmptyResults/EmptyResults.js
closes inveniosoftware/invenio-app-rdm#763
=> EmptyResults: pass props down to rendered element

src/lib/components/Sort/Sort.js
Adding possibility for accessible name to the search results sort dropdown
=> A11y: Sort dropdown ARIA label

src/lib/components/EmptyResults/index.js
* needed by https://github.com/inveniosoftware/invenio-app-rdm/pull/1241
=> EmptyResults: allow custom reset query

src/lib/components/ResultsPerPage/ResultsPerPage.js, src/lib/components/Sort/Sort.js, src/lib/components/SortBy/SortBy.js, src/lib/components/SortOrder/SortOrder.js
*Adds "selectOnNavigation=false" to not submit each option as keyboard-only user navigates among them with the down arrow
*Adds aria-labels for screenreaders
closes https://github.com/inveniosoftware/react-searchkit/issues/220
Please describe briefly your pull request.
:rotating_light: Please review the [guidelines for contributing](https://invenio.readthedocs.io/en/latest/community/contributing/contribution-guide.html) to Invenio.
> Green light on all GitHub Actions status checks is required in order to merge your PR. Check your code additions will fail neither code linting checks nor tests and will not decrease test coverage.
See [copyright and license policy](https://invenio.readthedocs.io/en/latest/community/contributing/maintainers-guide/copyri …
=> Update dropdowns for a11y

package-lock.json, package.json, src/lib/components/AutocompleteSearchBar/AutocompleteSearchBar.js, src/lib/components/Pagination/Pagination.js, src/lib/components/SearchBar/SearchBar.js
Closes https://github.com/inveniosoftware/invenio-administration/issues/129
=> pagination: navigate to previous page if current page is empty

.gitignore, CHANGES.md, package-lock.json, package.json, src/lib/components/BucketAggregation/BucketAggregation.js
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release: v2.2.1

CHANGES.md, package-lock.json, package.json
Please describe briefly your pull request.
Ticks in all boxes and 🟢 on all GitHub actions status checks are required to merge:
**Third-party code**
If you've added [third-party code (copy/pasted or new dependencies)](https://inveniordm.docs.cern.ch/develop/best-practices/commits/#third-party-codedependencies), please reach out to an [architect](https://github.com/orgs/inveniosoftware/teams/architects/members).
**Reminder**
By using GitHub, you have already agreed to the [GitHub’s Terms of Service](https://help.github.com/articles/github-terms-of-service/#6-contributions-under-repository-license) including that:
1. You license your contribution under the same terms as the current repository’s license.
2. You agree that you have the right to license …
=> release: v2.2.2

src/lib/components/BucketAggregation/BucketAggregationValues.js, src/lib/components/ReactSearchKit/ReactSearchKit.js, src/lib/state/selectors/query.test.js
Closes https://github.com/inveniosoftware/react-searchkit/issues/259
=> selector: Allow the same value in multiple children aggregations

docs/docs/components/results_grid.md, docs/docs/components/results_list.md, docs/docs/components/results_multi_layout.md, src/lib/components/ResultsGrid/ResultsGrid.js, src/lib/components/ResultsList/ResultsList.js, src/lib/components/ResultsMultiLayout/ResultsMultiLayout.js
* closes https://github.com/CERNDocumentServer/cds-rdm/issues/198
=> search results: render Mathjax in the results list and grid
