inveniosoftware/react-searchkit

docs/docs/components/results_per_page.md
In the Documentation it mentions ``ResultsPerPages``, note the last "s". However, the actual component name is ``ResultsPerPage`` therefore a mere copy-paste from the docs doeskin work and makes the user have to go to GiTHub, look for the component etc.
=> rename component doc of ResultsPerPage

docs/docs/connect_your_rest_apis.md, src/lib/api/contrib/elasticsearch/ESSearchApi.js, src/lib/api/contrib/elasticsearch/ESSearchApi.test.js, src/lib/api/contrib/invenio/InvenioSearchApi.js, src/lib/api/contrib/invenio/InvenioSearchApi.test.js
=> searchApi: fix "url" axios config override

src/lib/api/UrlHandlerApi.js, src/lib/api/contrib/elasticsearch/ESRequestSerializer.js, src/lib/api/contrib/elasticsearch/ESResponseSerializer.js, src/lib/api/contrib/elasticsearch/ESSearchApi.js, src/lib/api/contrib/invenio/InvenioRequestSerializer.js, src/lib/api/contrib/invenio/InvenioResponseSerializer.js, src/lib/api/contrib/invenio/InvenioSearchApi.js, src/lib/api/contrib/invenio/InvenioSuggestionApi.js, src/lib/components/ReactSearchKit/ReactSearchKit.test.js
=> api: use class methods instead of arrow functions

CHANGES.md, package.json, src/lib/state/selectors/query.js, src/lib/state/selectors/query.test.js
`updateQueryState` accepts only one filter a time. The intention of this pr is to be able to submit multiple filters at once. This is useful for example when we want to replace a filter.
=> global: updateQueryState support for multiple filters

docs/docs/components/count.md, docs/docs/components/results_per_page.md, docs/docs/components/sort.md, docs/docs/components/sort_by.md, docs/docs/components/sort_order.md, src/demos/cern-videos/Results.js, src/demos/elasticsearch/Results.js, src/demos/zenodo/Results.js, src/lib/components/Count/Count.js, src/lib/components/ResultsPerPage/ResultsPerPage.js, src/lib/components/Sort/Sort.js, src/lib/components/SortBy/SortBy.js, src/lib/components/SortOrder/SortOrder.js
=> global: add prefix and suffix props

src/lib/storeConfig.js
The initial values for pagination and results per page should be "undefined" as the others, so that:
* if the ResultsPerPage or Pagination components are not mounted, the value stays undefined and it is not added to the query string sent to the backend
* if the components are mounted, then the `defaultValue` of the component will be set
=> global: fix initial query state values

src/lib/components/SearchBar/SearchBar.js
- Moved functionality from Element to the parent component SearchBar, so that we can supply them to the Element that overrides.
=> components: SearchBar functions override

CHANGES.md, package.json, src/lib/components/BucketAggregation/BucketAggregation.js, src/lib/components/BucketAggregation/BucketAggregationValues.js
* You can override the `agg.bucket` label by injecting a `label` key to
the `agg.buckets` items
=> aggs: remove valueLabels property

docs/docs/components/react_search_kit.md, docs/docs/components/sort.md, src/demos/cern-videos/App.js, src/demos/zenodo/App.js, src/lib/api/contrib/invenio/InvenioSearchApi.js, src/lib/components/Bootstrap/Bootstrap.js, src/lib/components/Bootstrap/Bootstrap.test.js, src/lib/components/BucketAggregation/BucketAggregationValues.js, src/lib/components/ReactSearchKit/ReactSearchKit.js, src/lib/components/ReactSearchKit/ReactSearchKit.test.js, src/lib/components/Toggle/Toggle.js, src/lib/state/actions/query.js, src/lib/state/actions/query.test.js, src/lib/state/reducers/app.js, src/lib/state/reducers/index.js, src/lib/state/reducers/query.js, src/lib/store.js, src/lib/storeConfig.js
* introduces a new prop to define which sorting to use on empty query
string
* adds a new private app state to the store to keep track if the user
has selected a new sorting and what was the initial sorting before
change
* adds tests
* changes documentation
* closes #111
=> RSK: implement sorting on empty query string

package-lock.json, src/lib/api/UrlHandlerApi.js, src/lib/components/Bootstrap/index.js, src/lib/state/actions/query.js, src/lib/state/reducers/query.js, src/lib/state/reducers/results.js
* fixes url history not updating the internal state
* closes inveniosoftware/react-invenio-app-ils#274
Tested on zenodo demo and on ILS. Also tested on CDS videos demo which has disabled support for url handling.
It may not be the best way to do it, but it works. I'm preventing the url from being updated twice: this is a workaround (I hope temporary) because the url is replaced twice, and even though the state is equivalent in both cases the order of the attributes is not.
Open to suggestions.
=> fix url not updating state

src/demos/App.js, src/lib/api/contrib/elasticsearch/ESSearchApi.js, src/lib/api/contrib/invenio/InvenioSearchApi.js, src/lib/api/errors.js, src/lib/state/actions/query.js, src/lib/state/actions/query.test.js, src/lib/state/reducers/results.js, src/lib/store.js
* when a specific sorting is defined in the URL params, the automatic
change of sorting when query string is defined or empty will not have
effect.
* changed the concurrency issue by replacing the query state in the
results state check with the cancelling of previous axios requests
=> Disable change of sorting when defined in URL params

src/lib/components/BucketAggregation/BucketAggregationValues.js, src/lib/components/Count/Count.js
Applied for Count & BucketAggregation
closes #169
=> count: format toLocaleString

CHANGES.md, package-lock.json, package.json, src/lib/api/contrib/invenio/InvenioSearchApi.js, src/lib/state/actions/query.js, src/lib/state/reducers/query.js
closes inveniosoftware/invenio-app-rdm#531
When the action `resetQuery` is triggered there is no way to choose how to reset the query state. This PR gives the resetQuery action a payload that can be passed from components that override e.g the EmptyResults component. By doing that you can control the default query after the reset action is triggered!
=> components: pass payload to resetQuery

src/lib/components/SearchBar/SearchBar.js
Fixed search bar's query text.
- Query text was cleared after the query being submitted. 
Note: the search bar component might not be fully uncontrolled. A new issue (https://github.com/inveniosoftware/react-searchkit/issues/225) was created for that matter, in order to perform a more thorough analysis.
=> components: fix SearchBar text missing on input

src/lib/components/Pagination/Pagination.js
Closes https://github.com/zenodo/zenodo-rdm/issues/217
Adds maxTotalResults to limit the number of pages (default max 10k results visible).
=> pagination: add maxTotalResults to limit number of pages

src/lib/components/Pagination/Pagination.js
Closes https://github.com/zenodo/zenodo-rdm/issues/217
Adds `maxTotalResults` as part of the `options` prop in `<Pagination/>`
=> pagination: add maxTotalResults prop

src/lib/components/BucketAggregation/BucketAggregation.js
* closes https://github.com/zenodo/rdm-project/issues/218
In case only 1 bucket is present, it doesn't make sense to show it.
Facets in case 2 types of visibility:
Facets in case only public visibility:
=> bucket aggregations: render only if several buckets

src/lib/components/BucketAggregation/BucketAggregationValues.js
Closes https://github.com/zenodo/zenodo-rdm/issues/458
- Adds id to `Checkbox` in `BucketAggregationValues` (needed for label to be related correctly)
=> bucket aggregation: add id to checkbox

src/lib/api/contrib/invenio/InvenioRequestSerializer.js, src/lib/api/contrib/invenio/InvenioRequestSerializer.test.js
The nested facets are not working properly. A request like `f=type%3ADataset&f=type%3ADocumentation%2Bsubtype%3AAbout` gets translated into `type=Dataset&type=Documentation&subtype=About`, instead of `type=Dataset&subtype=About`.
Note that the comments in the code (line 45-60) were correct. The implementation was different :-)
=> InvenioSerializer: Remove parent category in nested filters

src/lib/components/ResultsGrid/ResultsGrid.js
Closes https://github.com/zenodo/rdm-project/issues/567
- I believe this was a bug, as it is passed in the same way for `ResultsList`, and also makes it easier to override this way.
=> results grid: pass correct value to results prop

docs/docs/components/pagination.md, docs/docs/components/results_per_page.md, src/lib/components/Pagination/Pagination.js, src/lib/components/ResultsPerPage/ResultsPerPage.js
> Please describe briefly your pull request.
Added a prop that allows to program Pagination and ResultsPerPage components to not render in certain conditions (when there are less results than resultsPerPage setting). If unused the components behave same as before.
=> allow for Pagination and ResultsPerPage to be hidden on few results
